parameters:
    botman_config:
        telegram: { token: '%env(TELEGRAM_BOT_API_TOKEN)%' }

services:
    _defaults:
        autowire: true

    BotMan\BotMan\BotManFactory:
        class: BotMan\BotMan\BotManFactory

    BotMan\BotMan\Interfaces\HttpInterface:
        class: App\Bot\GuzzleHttpClient

    app.request:
        class: Symfony\Component\HttpFoundation\RequestStack
        factory: ['@request_stack', getCurrentRequest]

    BotMan\Drivers\Telegram\TelegramDriver:
        class: BotMan\Drivers\Telegram\TelegramDriver
        arguments:
            $request: '@app.request'
            $config: '%botman_config%'

    BotMan\BotMan\BotMan:
        factory: 'BotMan\BotMan\BotManFactory:create'
        arguments: ['%botman_config%']
        calls:
            - method: setDriver
              arguments: ['@BotMan\Drivers\Telegram\TelegramDriver']
            - method: setContainer
              arguments: ['@service_container']
