services:
    _defaults:
        autowire: true

    BotMan\BotMan\BotManFactory:
        class: BotMan\BotMan\BotManFactory

    BotMan\BotMan\Interfaces\HttpInterface:
        class: App\Bot\GuzzleHttpClient

    BotMan\BotMan\Drivers\DriverManager:
        arguments: ['%botman_config%', '@BotMan\BotMan\Interfaces\HttpInterface']
        calls:
            - method: loadDriver
              arguments: ['BotMan\Drivers\Telegram\TelegramDriver']

    BotMan\Drivers\Telegram\TelegramDriver:
        factory: 'BotMan\BotMan\Drivers\DriverManager:loadFromName'
        arguments: ['BotMan\Drivers\Telegram\TelegramDriver', '%botman_config%']

    BotMan\BotMan\BotMan:
        factory: 'BotMan\BotMan\BotManFactory:create'
        arguments: ['%botman_config%']
        calls:
            - method: setDriver
              arguments: ['@BotMan\Drivers\Telegram\TelegramDriver']
            - method: setContainer
              arguments: ['@service_container']
