services:
  - docker

before_install:
  - docker-compose -f docker-compose.test.yml run --rm php composer install
  - docker-compose -f docker-compose.test.yml run --rm php bin/console doctrine:database:create --if-not-exists --env=test
  - docker-compose -f docker-compose.test.yml run --rm php bin/console doctrine:migrations:migrate --env=test --no-interaction

script:
  - docker-compose -f docker-compose.test.yml run --rm php vendor/bin/simple-phpunit --stop-on-failure
