version: '3'

services:
    db:
        build:
            context: ./docker/mysql
        hostname: db
        ports:
            - 3306:3306
        volumes:
            - mysql-tmpfs:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ALLOW_EMPTY_PASSWORD: 'true'

    php:
        build:
            context: ./docker/php
            args:
                APP_ENV: ${APP_ENV}
        hostname: php
        restart: always
        depends_on:
            - db
        ports:
            - 9000:9000
        volumes:
            - .:/app:cached
            - ~/.vimrc:/root/.vimrc:cached
            - ~/.bashrc:/root/.bashrc:cached
        working_dir: /app
        environment:
            APP_ENV: ${APP_ENV}
            APP_SECRET: ${APP_SECRET}
            MAILER_URL: ${MAILER_URL}
            ENQUEUE_DSN: ${ENQUEUE_DSN}
            TELEGRAM_BOT_NAME: 'labelbot'
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DBNAME: ${MYSQL_DBNAME}
            MYSQL_DBNAME_TEST: ${MYSQL_DBNAME_TEST}
            MYSQL_HOST: ${MYSQL_HOST}

volumes:
    mysql-tmpfs:
        driver: local
        driver_opts:
            device: tmpfs
            type: tmpfs
            o: size=1024m