version: '3'

services:
    db:
        build:
            context: ./docker/mysql
        hostname: db
        ports:
            - 3306:3306
        volumes:
            - ./var/database:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    php:
        build:
            context: ./docker/php
            args:
                APP_ENV: ${APP_ENV}
        hostname: php
        restart: always
        depends_on:
            - db
        ports:
            - 9000:9000
        volumes:
            - .:/app:cached
            - ~/.vimrc:/root/.vimrc:cached
            - ~/.bashrc:/root/.bashrc:cached
        working_dir: /app
        environment:
            APP_ENV: ${APP_ENV}
            APP_SECRET: ${APP_SECRET}
            TELEGRAM_ADMIN_CHAT_ID: ${TELEGRAM_ADMIN_CHAT_ID}
            TELEGRAM_BOT_NAME: ${TELEGRAM_BOT_NAME}
            TELEGRAM_BOT_API_TOKEN: ${TELEGRAM_BOT_API_TOKEN}
            SENTRY_DSN: ${SENTRY_DSN}
            REDIS_HOST: ${REDIS_HOST}
            REDIS_PORT: ${REDIS_PORT}
            MAILER_URL: ${MAILER_URL}
            ENQUEUE_DSN: ${ENQUEUE_DSN}
            RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
            RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DBNAME: ${MYSQL_DBNAME}
            MYSQL_DBNAME_TEST: ${MYSQL_DBNAME_TEST}
            MYSQL_HOST: ${MYSQL_HOST}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    nginx:
        build:
            context: ./docker/nginx
        hostname: nginx
        depends_on:
            - db
            - php
        ports:
            - 80:80
        volumes:
            - .:/app:cached

    rabbitmq:
        image: rabbitmq:3.7.5-management
        hostname: app-rabbitmq
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - ./var/data/rabbitmq:/var/lib/rabbitmq/mnesia/rabbit@app-rabbitmq:cached
        environment:
            RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
            RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}

    redis:
      image: redis:3.0
      hostname: redis
      ports:
        - 6379:6379