version: '3'

services:
    db:
        image: mysql:5.7.22
        container_name: labelbot_db
        hostname: db
        volumes:
            - mysql-tmpfs:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: rootpwd
            MYSQL_DATABASE: labelbot_test

    php:
        container_name: labelbot_php
        build:
            context: php
            args:
                APP_ENV: test
        hostname: php
        restart: always
        depends_on:
            - db
        volumes:
            - ..:/app:cached
        working_dir: /app
        environment:
            APP_ENV: test
            APP_SECRET: secret
            MAILER_URL: ${MAILER_URL}
            ENQUEUE_DSN: ${ENQUEUE_DSN}
            TELEGRAM_ADMIN_CHAT_ID: '1'
            TELEGRAM_BOT_NAME: 'labelbot'
            TELEGRAM_BOT_API_TOKEN: 'token'
            MYSQL_USER: root
            MYSQL_PASSWORD: rootpwd
            MYSQL_DBNAME: labelbot_test
            MYSQL_HOST: db

volumes:
    mysql-tmpfs:
        driver: local
        driver_opts:
            device: tmpfs
            type: tmpfs
            o: size=1024m