index:
    path: /
    controller: App\Bot\WebhookProcessor::handleTelegramRequest
    methods: [GET, POST]

email_confirm:
    path: /email/confirm/{confirmationToken}
    controller: App\Bot\Controller\EmailController::confirmEmail
    methods: [POST]
